# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"\xaf\x01\n\x05Robot\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06powers\x18\x03 \x03(\t\x12\x17\n\x0bspeed_level\x18\n \x01(\x05\x42\x02\x18\x01\x12#\n\x06helper\x18\x0b \x01(\x0b\x32\x13.robot.Robot.Helper\x1a$\n\x06Helper\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\tJ\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07R\x05laserR\x05\x61gile*)\n\x08SCENARIO\x12\x08\n\x04\x43ITY\x10\x00\x12\t\n\x05SPACE\x10\x01\x12\x08\n\x04MALL\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOT.fields_by_name['speed_level']._options = None
  _ROBOT.fields_by_name['speed_level']._serialized_options = b'\030\001'
  _SCENARIO._serialized_start=200
  _SCENARIO._serialized_end=241
  _ROBOT._serialized_start=23
  _ROBOT._serialized_end=198
  _ROBOT_HELPER._serialized_start=136
  _ROBOT_HELPER._serialized_end=172
# @@protoc_insertion_point(module_scope)
